export default {
  allProducts: [
    // {
    //   id: 1,
    //   imgUrl: "/img/1.png",
    //   gender: "male",
    //   model: "Чоловічі Кросівки Nike Blazer Mid Suede",
    //   price: 5400,
    // },
    // {
    //   id: 2,
    //   imgUrl: "/img/2.png",
    //   gender: "male",
    //   model: "Чоловічі Кросівки Nike Air Max 270",
    //   price: 6300,
    // },
    // {
    //   id: 3,
    //   imgUrl: "/img/3.png",
    //   gender: "male",
    //   model: "Чоловічі Кросівки Nike Blazer Mid Suede",
    //   price: 7200,
    // },
    // {
    //   id: 4,
    //   imgUrl: "/img/4.png",
    //   gender: "unisex",
    //   model: "Кросівки Puma X Aka Boku Future Rider",
    //   price: 3700,
    // },
    // {
    //   id: 5,
    //   imgUrl: "/img/5.png",
    //   gender: "male",
    //   model: "Чоловічі Кросівки Under Armour Curry 8",
    //   price: 5400,
    // },
    // {
    //   id: 6,
    //   imgUrl: "/img/6.png",
    //   gender: "male",
    //   model: "Чоловічі Кросівки Nike Kyrie 7",
    //   price: 6300,
    // },
    // {
    //   id: 7,
    //   imgUrl: "/img/7.png",
    //   gender: "male",
    //   model: "Чоловічі Кросівки Jordan Air Jordan 11",
    //   price: 7200,
    // },
    // {
    //   id: 8,
    //   imgUrl: "/img/8.png",
    //   gender: "unisex",
    //   model: "Чоловічі Кросівки Nike LeBron XVIII",
    //   price: 3700,
    // },
    // {
    //   id: 9,
    //   imgUrl: "/img/9.png",
    //   gender: "male",
    //   model: "Чоловічі Кросівки Nike Lebron XVIII Low",
    //   price: 5400,
    // },
    // {
    //   id: 10,
    //   imgUrl: "/img/10.png",
    //   gender: "male",
    //   model: "Чоловічі Кросівки Nike Kyrie Flytrap IV",
    //   price: 5400,
    // },
  ],
  cartProducts: [],
  favouriteProducts: [],
  searchValue: "",
  isCartOpened: false,
};
